# Generated by Django 3.0.3 on 2020-09-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='layerinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50, unique=True)),
                ('geoserver_name', models.CharField(max_length=50, unique=True)),
                ('layer_type', models.CharField(choices=[('raster', 'Raster Layer'), ('vector', 'Vector Layer')], max_length=50)),
                ('style_name', models.CharField(blank=True, max_length=50, null=True)),
                ('admin_allowed', models.BooleanField(default=True)),
                ('user_allowed', models.BooleanField(default=False)),
            ],
        ),
    ]
