# Generated by Django 3.0.3 on 2020-09-10 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layerinfo',
            old_name='geoserver_name',
            new_name='geoserver_layer_name',
        ),
        migrations.AddField(
            model_name='layerinfo',
            name='store_layer_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
