# Generated by Django 3.0.3 on 2020-09-15 18:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200910_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerinfo',
            name='db_layer_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
